{{- if .Values.cloudProvider }}
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: {{ .Release.Name }}-cloud-creds
  namespace: openshift-cloud-credential-operator
spec:
  secretRef:
    name: {{ .Release.Name }}-cloud-creds
    namespace: {{ .Release.Namespace }}
  {{- if eq (toString .Values.ccoMode) "manual" }}
  cloudTokenPath: /var/run/secrets/openshift/serviceaccount/token
  {{- end }}
  {{- if eq .Values.cloudProvider "aws" }}
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
      {{- toYaml .Values.cloudCredentials.aws.statementEntries | nindent 6 }}
    {{- if eq (toString .Values.ccoMode) "manual" }}
    stsIAMRoleARN: {{ .Values.cloudCredentials.aws.stsIAMRoleARN | default "" | quote }}
    {{- end }}
  {{- else if eq .Values.cloudProvider "gcp" }}
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: GCPProviderSpec
    predefinedRoles:
      {{- toYaml .Values.cloudCredentials.gcp.permissions | nindent 6 }}
    {{- if eq (toString .Values.ccoMode) "manual" }}
    serviceAccountEmail: {{ .Values.cloudCredentials.gcp.serviceAccountEmail | default "" | quote }}
    {{- end }}
  {{- else if eq .Values.cloudProvider "azure" }}
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AzureProviderSpec
    roleBindings:
      {{- toYaml .Values.cloudCredentials.azure.roleBindings | nindent 6 }}
    {{- if eq (toString .Values.ccoMode) "manual" }}
    azureClientID: {{ .Values.cloudCredentials.azure.azureClientID | default "" | quote }}
    azureTenantID: {{ .Values.cloudCredentials.azure.azureTenantID | default "" | quote }}
    {{- end }}
    {{- with .Values.cloudCredentials.azure.azureSubscriptionID }}
    azureSubscriptionID: {{ . | quote }}
    {{- end }}
    {{- with .Values.cloudCredentials.azure.azureRegion }}
    azureRegion: {{ . | quote }}
    {{- end }}
  {{- end }}
{{- end }}
