apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: rhtpa-operator-bind-get-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: allow-get-ingress
subjects:
- kind: ServiceAccount
  name: rhtpa-operator-controller-manager
  namespace: placeholder
