apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: rhtpa-operator-bind-job
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-job
subjects:
- kind: ServiceAccount
  name: rhtpa-operator-controller-manager
