apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: rhtpa-demo-cloud-creds
  namespace: openshift-cloud-credential-operator
spec:
  secretRef:
    name: rhtpa-demo-cloud-creds      # must equal <cr-name>-cloud-creds
    namespace: trustify               # the CR's namespace
  cloudTokenPath: /var/run/secrets/openshift/serviceaccount/token
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec   # AWS
    statementEntries:
      - effect: Allow
        action:
          - "s3:GetObject"
          - "s3:PutObject"
          - "s3:DeleteObject"
          - "s3:ListBucket"
          - "s3:GetBucketLocation"
          - "s3:ListBucketMultipartUploads"
          - "s3:AbortMultipartUpload"
          - "s3:ListMultipartUploadParts"
        resource: "*"
