apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-job
subjects:
- kind: ServiceAccount
  name: rhtpa-operator-controller-manager
roleRef:
  kind: Role
  name: role-job
  apiGroup: rbac.authorization.k8s.io
