apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rhtpa-operator
    app.kubernetes.io/managed-by: kustomize
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-reader
subjects:
  - kind: ServiceAccount
    name: rhtpa-operator-controller-manager
    namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-get-ingress
subjects:
  - kind: ServiceAccount
    name: rhtpa-operator-controller-manager
roleRef:
  kind: Role
  name: allow-get-ingress
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-job
subjects:
  - kind: ServiceAccount
    name: rhtpa-operator-controller-manager
roleRef:
  kind: Role
  name: role-job
  apiGroup: rbac.authorization.k8s.io
