apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-job
  namespace: placeholder
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "delete"]
