{{- if .Values.modules.tlsConfigurator.enabled }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: tls-configurator
  namespace: openshift-ingress-operator
  labels:
    app.kubernetes.io/name: tls-configurator
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
    helm.sh/hook-weight: "10"
    helm.sh/hook: "pre-install,pre-upgrade"
    helm.sh/hook-delete-policy: before-hook-creation
{{- end }}
