{{- if .Values.modules.tlsConfigurator.enabled }}

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tls-configurator
  labels:
    app.kubernetes.io/name: tls-configurator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tls-configurator
subjects:
  - kind: ServiceAccount
    name: tls-configurator
    namespace: {{ .Release.Namespace }}
{{- end }}
